BASE=quay.io/mapillai/rhcos-base:latest
KBC_IMG=quay.io/trusted-execution-clusters/trustee-attester:centos-stream-without-tpm-v0.17.0
CLEVIS_PIN_IMG=quay.io/trusted-execution-clusters/clevis-pin-trustee:centos-stream-75015a5
IGNITION_IMG=quay.io/trusted-execution-clusters/ignition:centos-stream-5a45ee84
IMAGE_CONFIG=image-rhel-10.2.yaml
VERSION=10.2
STREAM=tec
ID=rhel
NAME=rhcos
DESCRIPTION=Red Hat Enterprise Linux CoreOS 10.2 for trusted execution cluster
